### PR TITLE
Support non-Linux, update package docs

### PR DESCRIPTION
**Pull request by huin**
I've managed to get the crate to work on Windows as well as Linux (my dependent project is attempting to be cross-platform). The approach was to provide a new platform-agnostic method, and only conditionally compile the other method that requires `memfd_create` which is a Linux-specific system call.

It might be possible to make the original method work on non-Linux platforms, but I don't know Windows (or other major operating systems) well enough to think of an approach that provides the same automatic clean-up operations without changing the method signature.

Also included some updates to the docs and fixes to doctests.

Both changes are in separate commits, in case you want to keep the changes separate in change history.

### CODE REVIEW

**Comment by huin** [comment]
Also, let me know if you're happy with this change (even with changes), but you might want https://github.com/sp1ritCS/tabula-rs/pull/2 merged in as well. I'm happy to rebase this PR with those changes in your repo to save you time.

**Comment by sp1ritCS** [comment]
>  The approach was to provide a new platform-agnostic method, and only conditionally compile the other method that requires memfd_create which is a Linux-specific system call.

I guess instead of locking parse_document behind "Linux" only, it'd be better if it uses memfd_create to create a temporary file on newer Linuxes and mkstemp (or whatever equivalent windows has) on other platforms.

`parse_document_into` can still be available, seems useful to have.

---

> but you might want #2 merged in as well

I'm aware of #2, and I'll look into getting it once I have access to my machine that has cargo installed.

---

I'm currently working on a (somewhat) similar project, where I the jar is part of .rodata and I use memfd to create a file that I can pass as classpath to the JVM. I intend to change that behavior to allow the library to run on non-linux platforms by implementing a classloader capable of reading a jar at a memory address (either using libzip or by implementing a custom URL handler, not sure yet) and I'm thinking about porting that then over into this project (not sure if I have to rewrite the native stuff in rust then or if I manage to get build.rs to compile the c code) as that'd avoid having implementees to pass in the jar path during initialization.

**Comment by huin** [comment]
That would be ideal, although I don't know offhand how to portably create a temporary file that is automatically deleted as reliably and immediately as `memfd_create`, and that can be returned as a `std::fs::File`. If we can do that, then that works for me. Certainly operating systems for which there is a proven and implemented mechanism could have their own implementation of `parse_document` with an identical signature, each of which could be progressively added+implemented over time if such solutions come up.

**Comment by sp1ritCS** [comment]
> I don't know offhand how to portably create a temporary file that is automatically deleted as reliably and immediately as memfd_create

On UNIXes that have a procfs like linux, mkstemp with an immediate unlink after should work and then pass /proc/$$/fd/&lt;fd&gt; onward.

win32 has a DELETE_ON_EXIT (or similar) flag on its CreateFile call. Certainly not as immediate as memfd, but I feel like its good enough.

**Comment by huin** [comment]
I've made a fresh attempt. I did try using the Windows API, and managed to get only so far with it, but wasn't happy with how complex it was getting (~3 implementations of `TmpFile` - certainly 3 implemenations of `TmpFile::new`). I've tried the `tempfile` crate, and it looks like it works well here to cover all operating systems, but I've retained the Linux-specific optimisation.

* I've added a test to check the properties that I believe that `TmpFile` needs.
* There's a little refactoring (`get_file` is now `into_file` and consumes `TmpFile` rather than borrowing).
* The `unsafe` regions are more limited to specific code for Linux.

Tests are passing on both my Linux and Windows machines.

**Comment by huin** [comment]
On some additional thinking that having the two implementations would increase the risk of one failing to be tested, I've added a further commit "test both temporary file implemenations on Linux", such that both implementations are tested on Linux (generic+Linux), rather than just the Linux implementation.

**Comment by sp1ritCS** [comment]
Thanks, I've rebased your commits (and reorganized some).

**Comment by huin** [comment]
Thanks!

**Pull request closed without merging**
